/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davidde' at '12/23/15 1:56 PM' with Gradle 2.6
 *
 * @author davidde, @date 12/23/15 1:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
